### ISSUE TITLE
202402.json should not be available yet?

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [gt-scheduler/crawler-v2#19]
Unless GT is releasing course schedules a semester ahead of time, then how is the crawler getting data for Spring 2024 semester? 

202302.json and 202402.json are different (course crns appear to be different, to start with), but locations seem to be the same based on a spot check.

Asking b/c gt-scheduler opens to Spring 2024 by default, and I went to wrong lecture hall b/c i thought it would open to Fall 2023 by defualt :P

**Comment by AlexanderPuckhaber** [comment]
Academic calendar: https://registrar.gatech.edu/calendar/ 

October 25, 2023 (Wed) | Schedule of Classes Available Online Spring 2024 Registration Event

Was OSCAR published for Spring 2024 earlier, by mistake, and the scraper has that data? If so, I would propose deleting 202402.json until we are sure it is available/accurate

**Comment by nhatnghiho** [comment]
On Oscar, if you go to "Browse Course Catalog", you'd be able to find Spring 2024 schedule published there.
